author: Valentin Knabel
author_url: https://twitter.com/vknabel
github_url: https://github.com/vknabel/Finite
module: Finite
module_version: 3.0.2
root_url: https://vknabel.github.io/Finite/
readme: README.md
output: docs/
theme: fullwidth
